<a href="https://colab.research.google.com/github/sadaf-iqbal17/Pytorch/blob/main/Numpy_for_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
np1 =np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
print(np1.shape)


[0 1 2 3 4 5 6 7 8 9]
(10,)


**#Range --- we need to give a range and the numpy array starting from 0 upto the given range is created**

In [4]:
np2 =np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


**#Steps -- declare teh range of the numpy array to  be created an d also tell the gap in numbers in the array**

In [5]:
np3 = np.arange(0,10,2)
print(np3)

[0 2 4 6 8]


**#Zeros -- we can also crteate an array of zeros by mentioning the number of items you want**

In [6]:
np4 = np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Multidimensional zeros -- this will create multi-dimensional array of zeros all we n eed is to mention the dimensions**

In [7]:
np5 = np.zeros((2, 10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Full -- create a numpy array of any number and at first place write the range**

In [8]:
np6 = np.full(6, (10))
print(np6)

[10 10 10 10 10 10]


**Multidimensional Full array**

In [9]:
np7 = np.full((2,10) , 6)
print(np7)

[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


**Converting Python list to Numpy arrays**

In [13]:
my_list = [1,2,3,4,5]
np8 = np.array(my_list)
print(np8)
print(np8[3])  #printing the number at the index 4

[1 2 3 4 5]
4


**Slicing numpy arrays -- Taking slicing or portions out of arrays**

In [16]:
np8 = np.array([1,2,3,4,5,6,7,8,9])
print(np8[1:5])   #returning the elements from 1 to 5
print(np8[3:])  #returning the elements startoing from 3 upto the end

[2 3 4 5]
[4 5 6 7 8 9]


**Return negative slices  --- from end to start**

In [22]:
print(np8[ -5: -1])   #this will start from the last n umber upto the 5th last but will not include the last digit in the output

[5 6 7 8]


**Slices with steps**

In [ ]:
print(np8[1:5:2])   #returning the numbers with gaps of 2 last number represents the gap

[2 4]


**Steps of entire array**

In [26]:
print(np8[::2])

[1 3 5 7 9]


**Slicing a 2D array**

In [29]:
np9 =np.array([[1,2,3,4,5], [6,7,8,9,0]])   #here [[1,2,3,4,5], [6,7,8,9,0]]  this is 1 2D array its elements are also arrays. [1,2,3,4,5], this is first element at 0 index and next is at 1 index
print(np9[1,3])    #if we want to print the item from any one dimension we will write dimension at first place and the index of the item in that dimension at second place

9


**Slice a 2D ARRAY**

In [32]:
print(np9[0:1 , 1:3])  #here 0:1 is for rows and 1:3 for columns
#0:1 means starting from 0 row but not including 1 it will just select the first array
#1:3 means from that selected array print the items from 1 to 3 but not including 3

[[2 3]]


**Slicing from both rows**

In [35]:
print(np9[0:2 , 1:3])    #0:2 will select both the arrays  and 1:3 declares which element to select from which array

[[2 3]
 [7 8]]


**Universal functions in numnpy**

SQUARE ROOT

In [37]:
np10= np.array([-3, -2, -1, 0 ,1 ,2 ,3 ,4, 5])
print(np.sqrt(np1))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


ABSOLUTE  -- changing negatives to positives

In [38]:
print(np.absolute(np10))

[3 2 1 0 1 2 3 4 5]


EXPONENTIALS

In [40]:
print(np.exp(np10))   #calculates e^x  where x is the numbers of the array

[4.97870684e-02 1.35335283e-01 3.67879441e-01 1.00000000e+00
 2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02]


MAX & MIN

In [42]:
print(np.max(np10))
print(np.min(np10))

5
-3


SIGN POSITIVE OR NEGATIVE

In [43]:
print(np.sign(np10))

[-1 -1 -1  0  1  1  1  1  1]


LOG

In [86]:
print(np.log(np10))

[3.4339872         nan        nan       -inf 0.         0.69314718
 1.09861229 1.38629436 1.60943791]


/tmp/ipykernel_450/1564278052.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(np10))
/tmp/ipykernel_450/1564278052.py:1: RuntimeWarning: invalid value encountered in log
  print(np.log(np10))


**Check the NUMPY documentation for going through all the universal functions**

**Copy Vs View**

CREATE A VIEW

In [57]:
np11 =np10.view()   #this will create a view of the np10
print(f'Original array {np10}')
print(f'Copied array {np11}')
#f'Original array {np10}'   this is the way of merging the expressions with the outputs
np10[0] =21

print(f'Original array {np10}')
print(f'Copied array {np11}')

#so when we change teh origional the view also changes  so we can say that it is a copy but still connected to the original

Original array [21 -2 -1  0  1  2  3  4  5]
Copied array [21 -2 -1  0  1  2  3  4  5]
Original array [21 -2 -1  0  1  2  3  4  5]
Copied array [21 -2 -1  0  1  2  3  4  5]


CREATE A COPY

In [69]:
# in this case copy is not connected to teh original if we make a change in any one the otyher will n ot change

np12 =np11.copy()
print(f'Original array {np11}')
print(f'Copied array {np12}')
np11[0] =100
print(f'Original array {np11}')
print(f'Copied array {np12}')

Original array [31 -2 -1  0  1  2  3  4  5]
Copied array [31 -2 -1  0  1  2  3  4  5]
Original array [100  -2  -1   0   1   2   3   4   5]
Copied array [31 -2 -1  0  1  2  3  4  5]


**Shape of Numpy arrays**

In [75]:
#lets find the shape of np9 =np.array([[1,2,3,4,5], [6,7,8,9,0]])
print(np9)
print(f'Shape of array 9 is {np9.shape}')
print(f'Shape of array 12 is {np12.shape}')

[[1 2 3 4 5]
 [6 7 8 9 0]]
Shape of array 9 is (2, 5)
Shape of array 12 is (9,)


Reshape to 2d ARRAYS

In [80]:
np13 =np.array([1,2,3,4,5,76,8,3,45,34,2,2])
print(np13.reshape(3,4))

[[ 1  2  3  4]
 [ 5 76  8  3]
 [45 34  2  2]]


RESHAPE TO 3D ARRAYS

In [82]:
np14 = np13.reshape(2, 3, 2)
print(np14)

[[[ 1  2]
  [ 3  4]
  [ 5 76]]

 [[ 8  3]
  [45 34]
  [ 2  2]]]


REFLATE TO 1D

In [83]:
print(np14.reshape(-1))

[ 1  2  3  4  5 76  8  3 45 34  2  2]


**Iterating numpy arrays**

In [93]:
np15 =np.array([[1,2,3,9,6], [4,5,6,7,7]])
for x in np15:
  print(x)
  for y in x:
    print(y)


[1 2 3 9 6]
1
2
3
9
6
[4 5 6 7 7]
4
5
6
7
7


In [96]:
#3D array
np16 =np.array([[[1,2,3,9,6], [4,5,6,7,7] ,[1,5,7,8,9]],[[1,2,3,9,6], [4,5,6,7,7] ,[1,5,7,8,9]]])
print(np16)
for x in np16:
  print(x)
print(np16.shape)

[[[1 2 3 9 6]
  [4 5 6 7 7]
  [1 5 7 8 9]]

 [[1 2 3 9 6]
  [4 5 6 7 7]
  [1 5 7 8 9]]]
[[1 2 3 9 6]
 [4 5 6 7 7]
 [1 5 7 8 9]]
[[1 2 3 9 6]
 [4 5 6 7 7]
 [1 5 7 8 9]]
(2, 3, 5)


**Sorting**

In [100]:
np17= np.array([8,5,8,3,9,2])
print(np.sort(np17))

[2 3 5 8 8 9]


**Searching through numpy arrays**

In [103]:
print(np16)
x= np.where(np16 ==4)
print(x)

[[[1 2 3 9 6]
  [4 5 6 7 7]
  [1 5 7 8 9]]

 [[1 2 3 9 6]
  [4 5 6 7 7]
  [1 5 7 8 9]]]
(array([0, 1]), array([1, 1]), array([0, 0]))


In [107]:
y = np.where(np1 % 2 !=0)
print(y)

(array([1, 3, 5, 7, 9]),)


**Filtering numpy arrays with boolean index list **

In [117]:
print(np17)
filtered = []
for x in np17:
  if x % 2 == 0:
    filtered.append(True)
  else:
    filtered.append(False)
print(filtered)
print(np17[filtered])


[8 5 8 3 9 2]
[True, False, True, False, False, True]
[8 8 2]


**Shortcut for filtered**

In [118]:
filtered = np17 %2 ==0
print(filtered)

[ True False  True False False  True]
