<a href="https://colab.research.google.com/github/sadaf-iqbal17/Pytorch/blob/main/Numpy_for_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
np1 =np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)
print(np1.shape)


[0 1 2 3 4 5 6 7 8 9]
(10,)


**#Range --- we need to give a range and the numpy array starting from 0 upto the given range is created**

In [4]:
np2 =np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


**#Steps -- declare teh range of the numpy array to  be created an d also tell the gap in numbers in the array**

In [5]:
np3 = np.arange(0,10,2)
print(np3)

[0 2 4 6 8]


**#Zeros -- we can also crteate an array of zeros by mentioning the number of items you want**

In [6]:
np4 = np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Multidimensional zeros -- this will create multi-dimensional array of zeros all we n eed is to mention the dimensions**

In [7]:
np5 = np.zeros((2, 10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Full --create a numpy array of any number    at first place write teh range **

In [8]:
np6 = np.full(6, (10))
print(np6)

[10 10 10 10 10 10]


**Multidimensional Full array**

In [9]:
np7 = np.full((2,10) , 6)
print(np7)

[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


**Converting Python list to Numpy arrays**

In [13]:
my_list = [1,2,3,4,5]
np8 = np.array(my_list)
print(np8)
print(np8[3])  #printing the number at the index 4

[1 2 3 4 5]
4


**Slicing numpy arrays -- Taking slicing or portions out of arrays**

In [16]:
np8 = np.array([1,2,3,4,5,6,7,8,9])
print(np8[1:5])   #returning the elements from 1 to 5
print(np8[3:])  #returning the elements startoing from 3 upto the end

[2 3 4 5]
[4 5 6 7 8 9]


**Return negative slices  --- from end to start**

In [22]:
print(np8[ -5: -1])   #this will start from the last n umber upto the 5th last but will not include the last digit in the output

[5 6 7 8]


**Slices with steps**

In [25]:
print(np8[1:5:2])   #returning the numbers with gaps of 2 last number represents the gap

[2 4]


**Steps of entire array**

In [26]:
print(np8[::2])

[1 3 5 7 9]


**Slicing a 2D array**